version: "3"
services:
    mysql-standalone:
        image: 'mysql:5.7'
        networks:
            - spring-boot-mysql-network
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=employeemanager
        ports:
            - "3308:3306"
    springboot-docker-container:
        image: springboot-docker-container
        ports:
            - "8085:8080"
        environment: 
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/employeemanager
            SPRING_DATASOURCE_USERNAME: "root"
            SPRING_DATASOURCE_PASSWORD: "root"
        build:
            context: "./"
            dockerfile: "Dockerfile"
        networks:
            spring-boot-mysql-network
        depends_on:
            - mysql-standalone

networks:
  spring-boot-mysql-network:
    driver: bridge